project:
  type: website
  output-dir: docs

website:
  title: "Luis A. Barboza"
  google-analytics: "G-MLB1VF5ECW"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

